// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/emsihyo/go.im/comps/bi/message.proto

/*
	Package bi is a generated protocol buffer package.

	It is generated from these files:
		github.com/emsihyo/go.im/comps/bi/message.proto

	It has these top-level messages:
		Message
*/
package bi

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_Emit     Message_Type = 0
	Message_Request  Message_Type = 1
	Message_Response Message_Type = 2
)

var Message_Type_name = map[int32]string{
	0: "Emit",
	1: "Request",
	2: "Response",
}
var Message_Type_value = map[string]int32{
	"Emit":     0,
	"Request":  1,
	"Response": 2,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0, 0} }

type Message struct {
	T Message_Type `protobuf:"varint,1,opt,name=T,proto3,enum=bi.Message_Type" json:"T,omitempty"`
	I uint64       `protobuf:"varint,2,opt,name=I,proto3" json:"I,omitempty"`
	M string       `protobuf:"bytes,3,opt,name=M,proto3" json:"M,omitempty"`
	A []byte       `protobuf:"bytes,4,opt,name=A,proto3" json:"A,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0} }

func (m *Message) GetT() Message_Type {
	if m != nil {
		return m.T
	}
	return Message_Emit
}

func (m *Message) GetI() uint64 {
	if m != nil {
		return m.I
	}
	return 0
}

func (m *Message) GetM() string {
	if m != nil {
		return m.M
	}
	return ""
}

func (m *Message) GetA() []byte {
	if m != nil {
		return m.A
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "bi.Message")
	proto.RegisterEnum("bi.Message_Type", Message_Type_name, Message_Type_value)
}
func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.T != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.T))
	}
	if m.I != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.I))
	}
	if len(m.M) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.M)))
		i += copy(dAtA[i:], m.M)
	}
	if len(m.A) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.A)))
		i += copy(dAtA[i:], m.A)
	}
	return i, nil
}

func encodeFixed64Message(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Message(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Message) Size() (n int) {
	var l int
	_ = l
	if m.T != 0 {
		n += 1 + sovMessage(uint64(m.T))
	}
	if m.I != 0 {
		n += 1 + sovMessage(uint64(m.I))
	}
	l = len(m.M)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.A)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func sovMessage(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Message) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Message{`,
		`T:` + fmt.Sprintf("%v", this.T) + `,`,
		`I:` + fmt.Sprintf("%v", this.I) + `,`,
		`M:` + fmt.Sprintf("%v", this.M) + `,`,
		`A:` + fmt.Sprintf("%v", this.A) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMessage(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field T", wireType)
			}
			m.T = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.T |= (Message_Type(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field I", wireType)
			}
			m.I = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.I |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field M", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.M = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field A", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.A = append(m.A[:0], dAtA[iNdEx:postIndex]...)
			if m.A == nil {
				m.A = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMessage
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMessage(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMessage = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/emsihyo/go.im/comps/bi/message.proto", fileDescriptorMessage)
}

var fileDescriptorMessage = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0xfb, 0x9b, 0x88, 0x16, 0x13, 0x55, 0x91, 0xa7, 0x88, 0xc1, 0x8a, 0x3a, 0x45, 0x42,
	0xd8, 0x12, 0x3d, 0x41, 0x23, 0x31, 0x64, 0xc8, 0x62, 0xe5, 0x02, 0x38, 0x32, 0xa9, 0x07, 0xe3,
	0x80, 0x93, 0xa1, 0x5b, 0x47, 0x8e, 0x81, 0x38, 0x0d, 0x23, 0x23, 0x23, 0xe4, 0x24, 0x28, 0x69,
	0x07, 0xb6, 0xf7, 0xbd, 0xa7, 0xef, 0xe9, 0xff, 0xa9, 0x6c, 0x6d, 0xbf, 0x1f, 0xb4, 0x68, 0xbc,
	0x93, 0xc6, 0x05, 0xbb, 0x3f, 0x78, 0xd9, 0x7a, 0x61, 0x9d, 0x6c, 0xbc, 0xeb, 0x82, 0xd4, 0x56,
	0x3a, 0x13, 0xc2, 0x63, 0x6b, 0x44, 0xf7, 0xea, 0x7b, 0xcf, 0x88, 0xb6, 0x37, 0x77, 0xff, 0xa4,
	0xd6, 0xb7, 0x5e, 0xce, 0x27, 0x3d, 0x3c, 0xcd, 0x34, 0xc3, 0x3c, 0x9d, 0x94, 0xcd, 0x11, 0x74,
	0x59, 0x9d, 0x9e, 0x30, 0x4e, 0x51, 0xa7, 0xc8, 0x90, 0xaf, 0xef, 0x13, 0xa1, 0xad, 0x38, 0xef,
	0x45, 0x7d, 0xe8, 0x8c, 0x42, 0xcd, 0x62, 0x8a, 0x32, 0x25, 0x19, 0xf2, 0x48, 0xa1, 0x9c, 0xa8,
	0x4a, 0x2f, 0x32, 0xe4, 0x57, 0x0a, 0xd5, 0x44, 0xbb, 0x34, 0xca, 0x90, 0xc7, 0x0a, 0xbb, 0xcd,
	0x2d, 0x8d, 0x26, 0x89, 0xad, 0x68, 0xf4, 0xe0, 0x6c, 0x9f, 0x2c, 0xd8, 0x35, 0x5d, 0x2a, 0xf3,
	0x32, 0x98, 0xd0, 0x27, 0x60, 0x31, 0x5d, 0x29, 0x13, 0x3a, 0xff, 0x1c, 0x4c, 0x42, 0x8a, 0xed,
	0xf7, 0x2f, 0x5f, 0x1c, 0x47, 0x8e, 0xcf, 0x91, 0xe3, 0x6b, 0xe4, 0xf8, 0x19, 0x39, 0xe8, 0xba,
	0xf1, 0x4e, 0x9c, 0x5b, 0x0b, 0x6d, 0x0b, 0x52, 0x94, 0x6f, 0xc0, 0x3b, 0xf0, 0x41, 0x48, 0x51,
	0xea, 0xcb, 0x39, 0xfe, 0xf6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x87, 0xeb, 0x03, 0x24, 0x01,
	0x00, 0x00,
}
